### PR TITLE
Close #350: Fix websocket memory leak

### LINKED ISSUE #350: Akka interop: akka-streams resources not released on WebSocket disconnection

### PR DESCRIPTION
**Pull request by greenhost87**

### CODE REVIEW

File: interop/akka/src/main/scala/korolev/akka/package.scala [hunk 1]
```diff
@@ -62,28 +62,33 @@ package object akka {
...
-              complete(response)
-            case _ =>
-              throw new RuntimeException // cannot happen
+
+          complete {
+            Effect[F].toFuture(korolevServer.ws(korolevRequest)).map {
+              case KorolevResponse(_, outStream, _, _) =>
+                val source = outStream
+                    .asAkkaSource
+                    .map(text => TextMessage.Strict(text))
```
Comment (Tvaroh) [inline interop/akka/src/main/scala/korolev/akka/package.scala:76]: `.map(TextMessage.Strict)` perhaps?

File: interop/akka/src/main/scala/korolev/akka/package.scala [hunk 2]
```diff
@@ -62,28 +62,33 @@ package object akka {
...
+
+                val sink = Flow[Message]
+                    .mapConcat {
+                      case tm: TextMessage.Strict => tm.text :: Nil
```
Comment (Tvaroh) [inline interop/akka/src/main/scala/korolev/akka/package.scala:80]: Those `Nil`s seem weird. I know they were here before. But shouldn't it be `mapAsync` waiting for `runWith` to complete and no `Nil`s?

Comment (Tvaroh) [reply interop/akka/src/main/scala/korolev/akka/package.scala:80]: Something like this:

```scala
.mapAsync(1) {
  case TextMessage.Strict(text) => Future.successful(text)
  case TextMessage.Streamed(textStream) => textStream.runWith(Sink.ignore)
  case bm: BinaryMessage => bm.dataStream.runWith(Sink.ignore)
}
.collect { case Some(text) => text }
```
