### PR TITLE
Fix #65: Cookie parsing problem

### LINKED ISSUE #65: Problems found by basic load test with artilery
We are using [Artillery framework](https://artillery.io/docs/gettingstarted.html) for load testing.  I launched basic quick load test for [routingExample](https://github.com/fomkin/korolev/blob/master/examples/routing/src/main/scala/RoutingExample.scala) `artillery quick --duration 20 --rate 5 -n 5 http://localhost:8181` , 

 I got that big stack trace (I recduced it a little) :
```
[ForkJoinPool-1-worker-1] ERROR org.http4s.blaze.pipeline.Stage - Error during 'handleRequest' of HttpServerStage
scala.MatchError: [Ljava.lang.String;@623a6f (of class [Ljava.lang.String;)
[ForkJoinPool-1-worker-1] INFO org.http4s.blaze.pipeline.Stage - Shutting down HttpPipeline at Tue Jan 31 10:48:06 EET 2017
[ForkJoinPool-1-worker-1] ERROR org.http4s.blaze.pipeline.Stage - NIO2 channel closed with an unexpected error
scala.MatchError: [Ljava.lang.String;@623a6f (of class [Ljava.lang.String;)
```

It seems like there are some problems in cookies handling.

### PR DESCRIPTION
**Pull request by Fly-Style**
Please, review this PR by fixing issue #65

### CODE REVIEW

File: examples/simple/src/scala/scala/SimpleExample.scala [hunk 1]
```diff
@@ -65,7 +65,7 @@ object SimpleExample extends KorolevBlazeServer {
   )
 }
 
-case class State(todos: Vector[State.Todo] = (0 to 2).toVector map {
+case class State(todos: Vector[State.Todo] = (0 to() 2).toVector map {
```
Comment (vsuharnikov) [inline examples/simple/src/scala/scala/SimpleExample.scala]: Is it really necessary?

File: server-blaze/src/main/scala/korolev/blazeServer/package.scala [hunk 2]
```diff
@@ -51,12 +51,20 @@ package object blazeServer {
...
         cookie = { key =>
           headers collectFirst {
-            case ("cookie", cookieExtractor(map))
+            case ("Cookie", cookieExtractor(map))
+              if map.contains(key) => map(key)
+
+            /* Different browsers can send http-headers with upper-case first literal,
+             * or whole word in lower-case
+             * */
+            case ("сookie", cookieExtractor(map))
```
Comment (vsuharnikov) [inline server-blaze/src/main/scala/korolev/blazeServer/package.scala]: How about ```case ("Cookie" | "cookie", …)``` ? Or something like:
```scala
case (name, cookieExtractor(map)) if name.toLowerCase == "cookie" && map.contains(key)
```

File: server-blaze/src/main/scala/korolev/blazeServer/package.scala [hunk 3]
```diff
@@ -129,7 +137,7 @@ package object blazeServer {
   private object cookieExtractor {
     def unapply(arg: String): Option[Map[String, String]] = Some {
       arg.split(';') map { part =>
-        val Array(name, content) = part.split("=", 1)
+        val Array(name, content) = part.split("=")
```
Comment (vsuharnikov) [inline server-blaze/src/main/scala/korolev/blazeServer/package.scala]: 1. What if there are multiple '=' ?
2. `'='` (Char) here is better, because with "=" used an overloaded method with regular expressions

File: server-blaze/src/main/scala/korolev/blazeServer/package.scala (hunk 2 above)
Comment (Fly-Style) [inline server-blaze/src/main/scala/korolev/blazeServer/package.scala]: You are right, sure.

File: server-blaze/src/main/scala/korolev/blazeServer/package.scala [hunk 4]
```diff
@@ -51,12 +51,20 @@ package object blazeServer {
...
+
+
       val korolevRequest = KorolevRequest(
         path = Router.Path.fromString(path),
         params,
         cookie = { key =>
           headers collectFirst {
-            case ("cookie", cookieExtractor(map))
+            case ("Cookie", cookieExtractor(map))
+              if map.contains(key) => map(key)
```
Comment (vsuharnikov) [inline server-blaze/src/main/scala/korolev/blazeServer/package.scala]: What is the "map" and what does it contain? Could you get it more relevant name?

File: examples/simple/src/scala/scala/SimpleExample.scala (hunk 1 above)
Comment (Fly-Style) [inline examples/simple/src/scala/scala/SimpleExample.scala]: No, I had troubles with syntax highlighting in my IDE, but now all right.

Comment (vsuharnikov) [inline examples/simple/src/scala/scala/SimpleExample.scala]: Also you could use "breakOut" here:
```scala
(0 to 2).map({ i => State.Todo(s"This is TODO #$i", done = false)})(breakOut)
```

it will convert the collection to the Vector in-place.

**Comment by fomkin** [comment]
1. Commits should be squashed
2. Next time use this notation for PR name: "Fix #65: Cookie parsing problem"

File: server-blaze/src/main/scala/korolev/blazeServer/package.scala [hunk 5]
```diff
@@ -129,7 +134,7 @@ package object blazeServer {
   private object cookieExtractor {
     def unapply(arg: String): Option[Map[String, String]] = Some {
       arg.split(';') map { part =>
-        val Array(name, content) = part.split("=", 1)
+        val Array(name, content) = part.split('=')
```
Comment (fomkin) [inline server-blaze/src/main/scala/korolev/blazeServer/package.scala]: It's broken. Look at this https://tools.ietf.org/html/rfc6265#section-4.2.1. `cookie-value` can contain various equal signs.

```
val s = "hello=world=earth"
val Array(name, content) = s.split("=", 2) // Thats correct
```
